//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspOracle.Models.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_SERVICIO
    {
        public int ID_DETALLE_SERVICIO { get; set; }
        public int ID_SERVICO { get; set; }
        public int ID_HUESPED { get; set; }
        public int VALOR_SERVICIO { get; set; }
        public int CODIGO_SERVICIO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_RES { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_RES { get; set; }
    }
}
