//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspOracle.Models.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_HABITACIONES
    {
        public int ID_DETALLE_HABITACION { get; set; }
        public int ID_ESTADO_HABITACION { get; set; }
        public int VALOR { get; set; }
        public int HUESPED_ID_HUESPED { get; set; }
        public int HABITACION_ID_HABITACION { get; set; }
        public int EMPLEADOS_ID_EMPLEADO { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual HABITACION HABITACION { get; set; }
        public virtual HUESPED HUESPED { get; set; }
    }
}
