//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspOracle.Models.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class HUESPED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HUESPED()
        {
            this.DETALLE_COMEDORES = new HashSet<DETALLE_COMEDORES>();
            this.DETALLE_HABITACIONES = new HashSet<DETALLE_HABITACIONES>();
        }
    
        public int ID_HUESPED { get; set; }
        public string NOMBRE_HUESPED { get; set; }
        public string APELLIDO_HUESPED { get; set; }
        public Nullable<int> RUT_HUESPED { get; set; }
        public string DV_RUT_HUESPED { get; set; }
        public Nullable<int> TELEFONO_HUESPED { get; set; }
        public string CORREO_HUESPED { get; set; }
        public int EMPRESA_ID_EMPRESA { get; set; }
        public Nullable<int> ID_ESTADO_HUESPED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COMEDORES> DETALLE_COMEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_HABITACIONES> DETALLE_HABITACIONES { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
