//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspOracle.Models.Resources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMEDORES> COMEDORES { get; set; }
        public virtual DbSet<DETALLE_COMEDORES> DETALLE_COMEDORES { get; set; }
        public virtual DbSet<DETALLE_HABITACIONES> DETALLE_HABITACIONES { get; set; }
        public virtual DbSet<DETALLE_SERVICIO> DETALLE_SERVICIO { get; set; }
        public virtual DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ESTADO_HABITACION> ESTADO_HABITACION { get; set; }
        public virtual DbSet<HABITACION> HABITACION { get; set; }
        public virtual DbSet<HUESPED> HUESPED { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<PERFILES_USUARIOS> PERFILES_USUARIOS { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<ORDEN_PEDIDO> ORDEN_PEDIDO { get; set; }
    
        public virtual int ACTUALIZAR_COMEDOR(Nullable<decimal> p_ID_COMEDOR, string p_NOMBRE_COMEDOR, Nullable<decimal> p_CAPACIDAD_COMEDOR, Nullable<decimal> p_ESTADO_COMEDOR)
        {
            var p_ID_COMEDORParameter = p_ID_COMEDOR.HasValue ?
                new ObjectParameter("P_ID_COMEDOR", p_ID_COMEDOR) :
                new ObjectParameter("P_ID_COMEDOR", typeof(decimal));
    
            var p_NOMBRE_COMEDORParameter = p_NOMBRE_COMEDOR != null ?
                new ObjectParameter("P_NOMBRE_COMEDOR", p_NOMBRE_COMEDOR) :
                new ObjectParameter("P_NOMBRE_COMEDOR", typeof(string));
    
            var p_CAPACIDAD_COMEDORParameter = p_CAPACIDAD_COMEDOR.HasValue ?
                new ObjectParameter("P_CAPACIDAD_COMEDOR", p_CAPACIDAD_COMEDOR) :
                new ObjectParameter("P_CAPACIDAD_COMEDOR", typeof(decimal));
    
            var p_ESTADO_COMEDORParameter = p_ESTADO_COMEDOR.HasValue ?
                new ObjectParameter("P_ESTADO_COMEDOR", p_ESTADO_COMEDOR) :
                new ObjectParameter("P_ESTADO_COMEDOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_COMEDOR", p_ID_COMEDORParameter, p_NOMBRE_COMEDORParameter, p_CAPACIDAD_COMEDORParameter, p_ESTADO_COMEDORParameter);
        }
    
        public virtual int ACTUALIZAR_EMPLEADO(Nullable<decimal> p_ID_EMPLEADO, string p_NOMBRE_EMPLEADO, string p_APELLIDO_AMPLEADO, Nullable<decimal> p_TELEFONO_EMPLEADO, string p_CORREO_EMPLEADO, Nullable<decimal> p_EDAD_EMPLEADO, string p_DIRECCION_EMPLEADO)
        {
            var p_ID_EMPLEADOParameter = p_ID_EMPLEADO.HasValue ?
                new ObjectParameter("P_ID_EMPLEADO", p_ID_EMPLEADO) :
                new ObjectParameter("P_ID_EMPLEADO", typeof(decimal));
    
            var p_NOMBRE_EMPLEADOParameter = p_NOMBRE_EMPLEADO != null ?
                new ObjectParameter("P_NOMBRE_EMPLEADO", p_NOMBRE_EMPLEADO) :
                new ObjectParameter("P_NOMBRE_EMPLEADO", typeof(string));
    
            var p_APELLIDO_AMPLEADOParameter = p_APELLIDO_AMPLEADO != null ?
                new ObjectParameter("P_APELLIDO_AMPLEADO", p_APELLIDO_AMPLEADO) :
                new ObjectParameter("P_APELLIDO_AMPLEADO", typeof(string));
    
            var p_TELEFONO_EMPLEADOParameter = p_TELEFONO_EMPLEADO.HasValue ?
                new ObjectParameter("P_TELEFONO_EMPLEADO", p_TELEFONO_EMPLEADO) :
                new ObjectParameter("P_TELEFONO_EMPLEADO", typeof(decimal));
    
            var p_CORREO_EMPLEADOParameter = p_CORREO_EMPLEADO != null ?
                new ObjectParameter("P_CORREO_EMPLEADO", p_CORREO_EMPLEADO) :
                new ObjectParameter("P_CORREO_EMPLEADO", typeof(string));
    
            var p_EDAD_EMPLEADOParameter = p_EDAD_EMPLEADO.HasValue ?
                new ObjectParameter("P_EDAD_EMPLEADO", p_EDAD_EMPLEADO) :
                new ObjectParameter("P_EDAD_EMPLEADO", typeof(decimal));
    
            var p_DIRECCION_EMPLEADOParameter = p_DIRECCION_EMPLEADO != null ?
                new ObjectParameter("P_DIRECCION_EMPLEADO", p_DIRECCION_EMPLEADO) :
                new ObjectParameter("P_DIRECCION_EMPLEADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_EMPLEADO", p_ID_EMPLEADOParameter, p_NOMBRE_EMPLEADOParameter, p_APELLIDO_AMPLEADOParameter, p_TELEFONO_EMPLEADOParameter, p_CORREO_EMPLEADOParameter, p_EDAD_EMPLEADOParameter, p_DIRECCION_EMPLEADOParameter);
        }
    
        public virtual int ACTUALIZAR_EMPRESA(Nullable<decimal> p_EMPRESAID, string p_RAZON_SOCIAL, string p_RUT_EMPRESA, string p_DV_RUT_EMPRESA, string p_CORREO, string p_DIRECCION, Nullable<decimal> p_TELEFONO, string p_NOMBREREP, string p_APELLIDOREP)
        {
            var p_EMPRESAIDParameter = p_EMPRESAID.HasValue ?
                new ObjectParameter("P_EMPRESAID", p_EMPRESAID) :
                new ObjectParameter("P_EMPRESAID", typeof(decimal));
    
            var p_RAZON_SOCIALParameter = p_RAZON_SOCIAL != null ?
                new ObjectParameter("P_RAZON_SOCIAL", p_RAZON_SOCIAL) :
                new ObjectParameter("P_RAZON_SOCIAL", typeof(string));
    
            var p_RUT_EMPRESAParameter = p_RUT_EMPRESA != null ?
                new ObjectParameter("P_RUT_EMPRESA", p_RUT_EMPRESA) :
                new ObjectParameter("P_RUT_EMPRESA", typeof(string));
    
            var p_DV_RUT_EMPRESAParameter = p_DV_RUT_EMPRESA != null ?
                new ObjectParameter("P_DV_RUT_EMPRESA", p_DV_RUT_EMPRESA) :
                new ObjectParameter("P_DV_RUT_EMPRESA", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            var p_NOMBREREPParameter = p_NOMBREREP != null ?
                new ObjectParameter("P_NOMBREREP", p_NOMBREREP) :
                new ObjectParameter("P_NOMBREREP", typeof(string));
    
            var p_APELLIDOREPParameter = p_APELLIDOREP != null ?
                new ObjectParameter("P_APELLIDOREP", p_APELLIDOREP) :
                new ObjectParameter("P_APELLIDOREP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_EMPRESA", p_EMPRESAIDParameter, p_RAZON_SOCIALParameter, p_RUT_EMPRESAParameter, p_DV_RUT_EMPRESAParameter, p_CORREOParameter, p_DIRECCIONParameter, p_TELEFONOParameter, p_NOMBREREPParameter, p_APELLIDOREPParameter);
        }
    
        public virtual int ACTUALIZAR_HABITACION(Nullable<decimal> p_ID_HABITACION, string p_NOMBRE_HABITACION, string p_TIPO_CAMA_HABITACION, string p_ACCESORIOS_HABITACION, Nullable<decimal> p_VALOR_HABITACION, Nullable<decimal> p_ID_ESTADO_H)
        {
            var p_ID_HABITACIONParameter = p_ID_HABITACION.HasValue ?
                new ObjectParameter("P_ID_HABITACION", p_ID_HABITACION) :
                new ObjectParameter("P_ID_HABITACION", typeof(decimal));
    
            var p_NOMBRE_HABITACIONParameter = p_NOMBRE_HABITACION != null ?
                new ObjectParameter("P_NOMBRE_HABITACION", p_NOMBRE_HABITACION) :
                new ObjectParameter("P_NOMBRE_HABITACION", typeof(string));
    
            var p_TIPO_CAMA_HABITACIONParameter = p_TIPO_CAMA_HABITACION != null ?
                new ObjectParameter("P_TIPO_CAMA_HABITACION", p_TIPO_CAMA_HABITACION) :
                new ObjectParameter("P_TIPO_CAMA_HABITACION", typeof(string));
    
            var p_ACCESORIOS_HABITACIONParameter = p_ACCESORIOS_HABITACION != null ?
                new ObjectParameter("P_ACCESORIOS_HABITACION", p_ACCESORIOS_HABITACION) :
                new ObjectParameter("P_ACCESORIOS_HABITACION", typeof(string));
    
            var p_VALOR_HABITACIONParameter = p_VALOR_HABITACION.HasValue ?
                new ObjectParameter("P_VALOR_HABITACION", p_VALOR_HABITACION) :
                new ObjectParameter("P_VALOR_HABITACION", typeof(decimal));
    
            var p_ID_ESTADO_HParameter = p_ID_ESTADO_H.HasValue ?
                new ObjectParameter("P_ID_ESTADO_H", p_ID_ESTADO_H) :
                new ObjectParameter("P_ID_ESTADO_H", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_HABITACION", p_ID_HABITACIONParameter, p_NOMBRE_HABITACIONParameter, p_TIPO_CAMA_HABITACIONParameter, p_ACCESORIOS_HABITACIONParameter, p_VALOR_HABITACIONParameter, p_ID_ESTADO_HParameter);
        }
    
        public virtual int ACTUALIZAR_HUESPED(Nullable<decimal> p_ID_HUESPUED, string p_NOMBRE_HUESPED, string p_APELLIDO_HUESPED, Nullable<decimal> p_RUT_HUESPED, string p_DV_RUT_HUESPED, Nullable<decimal> p_TELEFONO, string p_CORREO, Nullable<decimal> p_EMPRESA_ID)
        {
            var p_ID_HUESPUEDParameter = p_ID_HUESPUED.HasValue ?
                new ObjectParameter("P_ID_HUESPUED", p_ID_HUESPUED) :
                new ObjectParameter("P_ID_HUESPUED", typeof(decimal));
    
            var p_NOMBRE_HUESPEDParameter = p_NOMBRE_HUESPED != null ?
                new ObjectParameter("P_NOMBRE_HUESPED", p_NOMBRE_HUESPED) :
                new ObjectParameter("P_NOMBRE_HUESPED", typeof(string));
    
            var p_APELLIDO_HUESPEDParameter = p_APELLIDO_HUESPED != null ?
                new ObjectParameter("P_APELLIDO_HUESPED", p_APELLIDO_HUESPED) :
                new ObjectParameter("P_APELLIDO_HUESPED", typeof(string));
    
            var p_RUT_HUESPEDParameter = p_RUT_HUESPED.HasValue ?
                new ObjectParameter("P_RUT_HUESPED", p_RUT_HUESPED) :
                new ObjectParameter("P_RUT_HUESPED", typeof(decimal));
    
            var p_DV_RUT_HUESPEDParameter = p_DV_RUT_HUESPED != null ?
                new ObjectParameter("P_DV_RUT_HUESPED", p_DV_RUT_HUESPED) :
                new ObjectParameter("P_DV_RUT_HUESPED", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_EMPRESA_IDParameter = p_EMPRESA_ID.HasValue ?
                new ObjectParameter("P_EMPRESA_ID", p_EMPRESA_ID) :
                new ObjectParameter("P_EMPRESA_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_HUESPED", p_ID_HUESPUEDParameter, p_NOMBRE_HUESPEDParameter, p_APELLIDO_HUESPEDParameter, p_RUT_HUESPEDParameter, p_DV_RUT_HUESPEDParameter, p_TELEFONOParameter, p_CORREOParameter, p_EMPRESA_IDParameter);
        }
    
        public virtual int ACTUALIZAR_MENU(Nullable<decimal> p_ID_MENU, string p_NOMBRE_MENU, Nullable<decimal> p_TIPO_MENU, Nullable<decimal> p_ESTILO_MENU, string p_DESCRIPCION_MENU, Nullable<decimal> p_VALOR_MENU, Nullable<decimal> p_CANTIDAD_MENU, Nullable<decimal> p_ESTADO_MENU)
        {
            var p_ID_MENUParameter = p_ID_MENU.HasValue ?
                new ObjectParameter("P_ID_MENU", p_ID_MENU) :
                new ObjectParameter("P_ID_MENU", typeof(decimal));
    
            var p_NOMBRE_MENUParameter = p_NOMBRE_MENU != null ?
                new ObjectParameter("P_NOMBRE_MENU", p_NOMBRE_MENU) :
                new ObjectParameter("P_NOMBRE_MENU", typeof(string));
    
            var p_TIPO_MENUParameter = p_TIPO_MENU.HasValue ?
                new ObjectParameter("P_TIPO_MENU", p_TIPO_MENU) :
                new ObjectParameter("P_TIPO_MENU", typeof(decimal));
    
            var p_ESTILO_MENUParameter = p_ESTILO_MENU.HasValue ?
                new ObjectParameter("P_ESTILO_MENU", p_ESTILO_MENU) :
                new ObjectParameter("P_ESTILO_MENU", typeof(decimal));
    
            var p_DESCRIPCION_MENUParameter = p_DESCRIPCION_MENU != null ?
                new ObjectParameter("P_DESCRIPCION_MENU", p_DESCRIPCION_MENU) :
                new ObjectParameter("P_DESCRIPCION_MENU", typeof(string));
    
            var p_VALOR_MENUParameter = p_VALOR_MENU.HasValue ?
                new ObjectParameter("P_VALOR_MENU", p_VALOR_MENU) :
                new ObjectParameter("P_VALOR_MENU", typeof(decimal));
    
            var p_CANTIDAD_MENUParameter = p_CANTIDAD_MENU.HasValue ?
                new ObjectParameter("P_CANTIDAD_MENU", p_CANTIDAD_MENU) :
                new ObjectParameter("P_CANTIDAD_MENU", typeof(decimal));
    
            var p_ESTADO_MENUParameter = p_ESTADO_MENU.HasValue ?
                new ObjectParameter("P_ESTADO_MENU", p_ESTADO_MENU) :
                new ObjectParameter("P_ESTADO_MENU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_MENU", p_ID_MENUParameter, p_NOMBRE_MENUParameter, p_TIPO_MENUParameter, p_ESTILO_MENUParameter, p_DESCRIPCION_MENUParameter, p_VALOR_MENUParameter, p_CANTIDAD_MENUParameter, p_ESTADO_MENUParameter);
        }
    
        public virtual int ACTUALIZAR_PROVEEDOR(Nullable<decimal> p_ID_PROVEEDOR, string p_NOMBRE_PROVEEDOR, Nullable<decimal> p_CONTACTO_PROVEEDOR, string p_RUBRO_PROVEEDOR, string p_DIRECCION_PROVEEDOR, string p_CORREO_PROVEEDOR)
        {
            var p_ID_PROVEEDORParameter = p_ID_PROVEEDOR.HasValue ?
                new ObjectParameter("P_ID_PROVEEDOR", p_ID_PROVEEDOR) :
                new ObjectParameter("P_ID_PROVEEDOR", typeof(decimal));
    
            var p_NOMBRE_PROVEEDORParameter = p_NOMBRE_PROVEEDOR != null ?
                new ObjectParameter("P_NOMBRE_PROVEEDOR", p_NOMBRE_PROVEEDOR) :
                new ObjectParameter("P_NOMBRE_PROVEEDOR", typeof(string));
    
            var p_CONTACTO_PROVEEDORParameter = p_CONTACTO_PROVEEDOR.HasValue ?
                new ObjectParameter("P_CONTACTO_PROVEEDOR", p_CONTACTO_PROVEEDOR) :
                new ObjectParameter("P_CONTACTO_PROVEEDOR", typeof(decimal));
    
            var p_RUBRO_PROVEEDORParameter = p_RUBRO_PROVEEDOR != null ?
                new ObjectParameter("P_RUBRO_PROVEEDOR", p_RUBRO_PROVEEDOR) :
                new ObjectParameter("P_RUBRO_PROVEEDOR", typeof(string));
    
            var p_DIRECCION_PROVEEDORParameter = p_DIRECCION_PROVEEDOR != null ?
                new ObjectParameter("P_DIRECCION_PROVEEDOR", p_DIRECCION_PROVEEDOR) :
                new ObjectParameter("P_DIRECCION_PROVEEDOR", typeof(string));
    
            var p_CORREO_PROVEEDORParameter = p_CORREO_PROVEEDOR != null ?
                new ObjectParameter("P_CORREO_PROVEEDOR", p_CORREO_PROVEEDOR) :
                new ObjectParameter("P_CORREO_PROVEEDOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_PROVEEDOR", p_ID_PROVEEDORParameter, p_NOMBRE_PROVEEDORParameter, p_CONTACTO_PROVEEDORParameter, p_RUBRO_PROVEEDORParameter, p_DIRECCION_PROVEEDORParameter, p_CORREO_PROVEEDORParameter);
        }
    
        public virtual int ELIMINAR_COMEDOR(Nullable<decimal> p_COMEDORID)
        {
            var p_COMEDORIDParameter = p_COMEDORID.HasValue ?
                new ObjectParameter("P_COMEDORID", p_COMEDORID) :
                new ObjectParameter("P_COMEDORID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_COMEDOR", p_COMEDORIDParameter);
        }
    
        public virtual int ELIMINAR_EMPLEADO(Nullable<decimal> eMPLEADOID)
        {
            var eMPLEADOIDParameter = eMPLEADOID.HasValue ?
                new ObjectParameter("EMPLEADOID", eMPLEADOID) :
                new ObjectParameter("EMPLEADOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_EMPLEADO", eMPLEADOIDParameter);
        }
    
        public virtual int ELIMINAR_EMPRESA(Nullable<decimal> eMPRESAID)
        {
            var eMPRESAIDParameter = eMPRESAID.HasValue ?
                new ObjectParameter("EMPRESAID", eMPRESAID) :
                new ObjectParameter("EMPRESAID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_EMPRESA", eMPRESAIDParameter);
        }
    
        public virtual int ELIMINAR_HABITACION(Nullable<decimal> p_HABITACIONID)
        {
            var p_HABITACIONIDParameter = p_HABITACIONID.HasValue ?
                new ObjectParameter("P_HABITACIONID", p_HABITACIONID) :
                new ObjectParameter("P_HABITACIONID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_HABITACION", p_HABITACIONIDParameter);
        }
    
        public virtual int ELIMINAR_HUESPED(Nullable<decimal> hUESPEDID)
        {
            var hUESPEDIDParameter = hUESPEDID.HasValue ?
                new ObjectParameter("HUESPEDID", hUESPEDID) :
                new ObjectParameter("HUESPEDID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_HUESPED", hUESPEDIDParameter);
        }
    
        public virtual int ELIMINAR_MENU(Nullable<decimal> p_MENUID)
        {
            var p_MENUIDParameter = p_MENUID.HasValue ?
                new ObjectParameter("P_MENUID", p_MENUID) :
                new ObjectParameter("P_MENUID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_MENU", p_MENUIDParameter);
        }
    
        public virtual int ELIMINAR_PROVEEDOR(Nullable<decimal> pROVEEDORID)
        {
            var pROVEEDORIDParameter = pROVEEDORID.HasValue ?
                new ObjectParameter("PROVEEDORID", pROVEEDORID) :
                new ObjectParameter("PROVEEDORID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_PROVEEDOR", pROVEEDORIDParameter);
        }
    
        public virtual int INSERTAR_COMEDOR(string p_NOMBRE_COMEDOR, Nullable<decimal> p_CAPACIDAD_COMEDOR, Nullable<decimal> p_ESTADO_COMEDOR)
        {
            var p_NOMBRE_COMEDORParameter = p_NOMBRE_COMEDOR != null ?
                new ObjectParameter("P_NOMBRE_COMEDOR", p_NOMBRE_COMEDOR) :
                new ObjectParameter("P_NOMBRE_COMEDOR", typeof(string));
    
            var p_CAPACIDAD_COMEDORParameter = p_CAPACIDAD_COMEDOR.HasValue ?
                new ObjectParameter("P_CAPACIDAD_COMEDOR", p_CAPACIDAD_COMEDOR) :
                new ObjectParameter("P_CAPACIDAD_COMEDOR", typeof(decimal));
    
            var p_ESTADO_COMEDORParameter = p_ESTADO_COMEDOR.HasValue ?
                new ObjectParameter("P_ESTADO_COMEDOR", p_ESTADO_COMEDOR) :
                new ObjectParameter("P_ESTADO_COMEDOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_COMEDOR", p_NOMBRE_COMEDORParameter, p_CAPACIDAD_COMEDORParameter, p_ESTADO_COMEDORParameter);
        }
    
        public virtual int INSERTAR_DETALLE_COMEDOR(Nullable<decimal> p_ID_COMEDOR, Nullable<decimal> p_ID_HUESPED, Nullable<decimal> p_ID_EMPLEADO, Nullable<decimal> p_ID_MENU)
        {
            var p_ID_COMEDORParameter = p_ID_COMEDOR.HasValue ?
                new ObjectParameter("P_ID_COMEDOR", p_ID_COMEDOR) :
                new ObjectParameter("P_ID_COMEDOR", typeof(decimal));
    
            var p_ID_HUESPEDParameter = p_ID_HUESPED.HasValue ?
                new ObjectParameter("P_ID_HUESPED", p_ID_HUESPED) :
                new ObjectParameter("P_ID_HUESPED", typeof(decimal));
    
            var p_ID_EMPLEADOParameter = p_ID_EMPLEADO.HasValue ?
                new ObjectParameter("P_ID_EMPLEADO", p_ID_EMPLEADO) :
                new ObjectParameter("P_ID_EMPLEADO", typeof(decimal));
    
            var p_ID_MENUParameter = p_ID_MENU.HasValue ?
                new ObjectParameter("P_ID_MENU", p_ID_MENU) :
                new ObjectParameter("P_ID_MENU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_DETALLE_COMEDOR", p_ID_COMEDORParameter, p_ID_HUESPEDParameter, p_ID_EMPLEADOParameter, p_ID_MENUParameter);
        }
    
        public virtual int INSERTAR_DETALLE_HABITACION(Nullable<decimal> p_ID_ESTADO_HABITACION, Nullable<decimal> p_VALOR, Nullable<decimal> p_HUESPED_ID_HUESPED, Nullable<decimal> p_HABITACION_ID_HABITACION, Nullable<decimal> p_EMPLEADOS_ID_EMPLEADO)
        {
            var p_ID_ESTADO_HABITACIONParameter = p_ID_ESTADO_HABITACION.HasValue ?
                new ObjectParameter("P_ID_ESTADO_HABITACION", p_ID_ESTADO_HABITACION) :
                new ObjectParameter("P_ID_ESTADO_HABITACION", typeof(decimal));
    
            var p_VALORParameter = p_VALOR.HasValue ?
                new ObjectParameter("P_VALOR", p_VALOR) :
                new ObjectParameter("P_VALOR", typeof(decimal));
    
            var p_HUESPED_ID_HUESPEDParameter = p_HUESPED_ID_HUESPED.HasValue ?
                new ObjectParameter("P_HUESPED_ID_HUESPED", p_HUESPED_ID_HUESPED) :
                new ObjectParameter("P_HUESPED_ID_HUESPED", typeof(decimal));
    
            var p_HABITACION_ID_HABITACIONParameter = p_HABITACION_ID_HABITACION.HasValue ?
                new ObjectParameter("P_HABITACION_ID_HABITACION", p_HABITACION_ID_HABITACION) :
                new ObjectParameter("P_HABITACION_ID_HABITACION", typeof(decimal));
    
            var p_EMPLEADOS_ID_EMPLEADOParameter = p_EMPLEADOS_ID_EMPLEADO.HasValue ?
                new ObjectParameter("P_EMPLEADOS_ID_EMPLEADO", p_EMPLEADOS_ID_EMPLEADO) :
                new ObjectParameter("P_EMPLEADOS_ID_EMPLEADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_DETALLE_HABITACION", p_ID_ESTADO_HABITACIONParameter, p_VALORParameter, p_HUESPED_ID_HUESPEDParameter, p_HABITACION_ID_HABITACIONParameter, p_EMPLEADOS_ID_EMPLEADOParameter);
        }
    
        public virtual int INSERTAR_DETALLE_SERVICIO(Nullable<decimal> p_ID_SERVICIO, Nullable<decimal> p_ID_HUESPED, Nullable<decimal> p_VALOR_SERVICIO, Nullable<decimal> p_CODIGO_RESERVA, Nullable<System.DateTime> p_FECHA_INICIO, Nullable<System.DateTime> p_FECHA_FIN)
        {
            var p_ID_SERVICIOParameter = p_ID_SERVICIO.HasValue ?
                new ObjectParameter("P_ID_SERVICIO", p_ID_SERVICIO) :
                new ObjectParameter("P_ID_SERVICIO", typeof(decimal));
    
            var p_ID_HUESPEDParameter = p_ID_HUESPED.HasValue ?
                new ObjectParameter("P_ID_HUESPED", p_ID_HUESPED) :
                new ObjectParameter("P_ID_HUESPED", typeof(decimal));
    
            var p_VALOR_SERVICIOParameter = p_VALOR_SERVICIO.HasValue ?
                new ObjectParameter("P_VALOR_SERVICIO", p_VALOR_SERVICIO) :
                new ObjectParameter("P_VALOR_SERVICIO", typeof(decimal));
    
            var p_CODIGO_RESERVAParameter = p_CODIGO_RESERVA.HasValue ?
                new ObjectParameter("P_CODIGO_RESERVA", p_CODIGO_RESERVA) :
                new ObjectParameter("P_CODIGO_RESERVA", typeof(decimal));
    
            var p_FECHA_INICIOParameter = p_FECHA_INICIO.HasValue ?
                new ObjectParameter("P_FECHA_INICIO", p_FECHA_INICIO) :
                new ObjectParameter("P_FECHA_INICIO", typeof(System.DateTime));
    
            var p_FECHA_FINParameter = p_FECHA_FIN.HasValue ?
                new ObjectParameter("P_FECHA_FIN", p_FECHA_FIN) :
                new ObjectParameter("P_FECHA_FIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_DETALLE_SERVICIO", p_ID_SERVICIOParameter, p_ID_HUESPEDParameter, p_VALOR_SERVICIOParameter, p_CODIGO_RESERVAParameter, p_FECHA_INICIOParameter, p_FECHA_FINParameter);
        }
    
        public virtual int INSERTAR_EMPLEADOS(string nOMBRE_EMPLEADO, string aPELLIDO_EMPLEADO, Nullable<decimal> tELEFONO_EMPLEADO, string cORREO_EMPLEADO, Nullable<decimal> eDAD_EMPLEADO, string dIRECCION_EMPELADO, Nullable<decimal> iD_USUARIO, Nullable<decimal> iD_PERFIL)
        {
            var nOMBRE_EMPLEADOParameter = nOMBRE_EMPLEADO != null ?
                new ObjectParameter("NOMBRE_EMPLEADO", nOMBRE_EMPLEADO) :
                new ObjectParameter("NOMBRE_EMPLEADO", typeof(string));
    
            var aPELLIDO_EMPLEADOParameter = aPELLIDO_EMPLEADO != null ?
                new ObjectParameter("APELLIDO_EMPLEADO", aPELLIDO_EMPLEADO) :
                new ObjectParameter("APELLIDO_EMPLEADO", typeof(string));
    
            var tELEFONO_EMPLEADOParameter = tELEFONO_EMPLEADO.HasValue ?
                new ObjectParameter("TELEFONO_EMPLEADO", tELEFONO_EMPLEADO) :
                new ObjectParameter("TELEFONO_EMPLEADO", typeof(decimal));
    
            var cORREO_EMPLEADOParameter = cORREO_EMPLEADO != null ?
                new ObjectParameter("CORREO_EMPLEADO", cORREO_EMPLEADO) :
                new ObjectParameter("CORREO_EMPLEADO", typeof(string));
    
            var eDAD_EMPLEADOParameter = eDAD_EMPLEADO.HasValue ?
                new ObjectParameter("EDAD_EMPLEADO", eDAD_EMPLEADO) :
                new ObjectParameter("EDAD_EMPLEADO", typeof(decimal));
    
            var dIRECCION_EMPELADOParameter = dIRECCION_EMPELADO != null ?
                new ObjectParameter("DIRECCION_EMPELADO", dIRECCION_EMPELADO) :
                new ObjectParameter("DIRECCION_EMPELADO", typeof(string));
    
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(decimal));
    
            var iD_PERFILParameter = iD_PERFIL.HasValue ?
                new ObjectParameter("ID_PERFIL", iD_PERFIL) :
                new ObjectParameter("ID_PERFIL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_EMPLEADOS", nOMBRE_EMPLEADOParameter, aPELLIDO_EMPLEADOParameter, tELEFONO_EMPLEADOParameter, cORREO_EMPLEADOParameter, eDAD_EMPLEADOParameter, dIRECCION_EMPELADOParameter, iD_USUARIOParameter, iD_PERFILParameter);
        }
    
        public virtual int INSERTAR_EMPRESA(string rAZON_SOCIAL, string rUT_EMPRESA, string dV_RUT_EMPRESA, string cORREO, string dIRECCION, Nullable<decimal> tELEFONO, string nOMBREREP, string aPELLIDOREP)
        {
            var rAZON_SOCIALParameter = rAZON_SOCIAL != null ?
                new ObjectParameter("RAZON_SOCIAL", rAZON_SOCIAL) :
                new ObjectParameter("RAZON_SOCIAL", typeof(string));
    
            var rUT_EMPRESAParameter = rUT_EMPRESA != null ?
                new ObjectParameter("RUT_EMPRESA", rUT_EMPRESA) :
                new ObjectParameter("RUT_EMPRESA", typeof(string));
    
            var dV_RUT_EMPRESAParameter = dV_RUT_EMPRESA != null ?
                new ObjectParameter("DV_RUT_EMPRESA", dV_RUT_EMPRESA) :
                new ObjectParameter("DV_RUT_EMPRESA", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(decimal));
    
            var nOMBREREPParameter = nOMBREREP != null ?
                new ObjectParameter("NOMBREREP", nOMBREREP) :
                new ObjectParameter("NOMBREREP", typeof(string));
    
            var aPELLIDOREPParameter = aPELLIDOREP != null ?
                new ObjectParameter("APELLIDOREP", aPELLIDOREP) :
                new ObjectParameter("APELLIDOREP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_EMPRESA", rAZON_SOCIALParameter, rUT_EMPRESAParameter, dV_RUT_EMPRESAParameter, cORREOParameter, dIRECCIONParameter, tELEFONOParameter, nOMBREREPParameter, aPELLIDOREPParameter);
        }
    
        public virtual int INSERTAR_HABITACION(string p_NOMBRE_HABITACION, string p_TIPO_CAMA_HABITACION, string p_ACCESORIOS_HABITACION, Nullable<decimal> p_VALOR_HABITACION, Nullable<decimal> p_ESTADO_HABITACION)
        {
            var p_NOMBRE_HABITACIONParameter = p_NOMBRE_HABITACION != null ?
                new ObjectParameter("P_NOMBRE_HABITACION", p_NOMBRE_HABITACION) :
                new ObjectParameter("P_NOMBRE_HABITACION", typeof(string));
    
            var p_TIPO_CAMA_HABITACIONParameter = p_TIPO_CAMA_HABITACION != null ?
                new ObjectParameter("P_TIPO_CAMA_HABITACION", p_TIPO_CAMA_HABITACION) :
                new ObjectParameter("P_TIPO_CAMA_HABITACION", typeof(string));
    
            var p_ACCESORIOS_HABITACIONParameter = p_ACCESORIOS_HABITACION != null ?
                new ObjectParameter("P_ACCESORIOS_HABITACION", p_ACCESORIOS_HABITACION) :
                new ObjectParameter("P_ACCESORIOS_HABITACION", typeof(string));
    
            var p_VALOR_HABITACIONParameter = p_VALOR_HABITACION.HasValue ?
                new ObjectParameter("P_VALOR_HABITACION", p_VALOR_HABITACION) :
                new ObjectParameter("P_VALOR_HABITACION", typeof(decimal));
    
            var p_ESTADO_HABITACIONParameter = p_ESTADO_HABITACION.HasValue ?
                new ObjectParameter("P_ESTADO_HABITACION", p_ESTADO_HABITACION) :
                new ObjectParameter("P_ESTADO_HABITACION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_HABITACION", p_NOMBRE_HABITACIONParameter, p_TIPO_CAMA_HABITACIONParameter, p_ACCESORIOS_HABITACIONParameter, p_VALOR_HABITACIONParameter, p_ESTADO_HABITACIONParameter);
        }
    
        public virtual int INSERTAR_HUESPED(string p_NOMBRE_HUESPED, string p_APELLIDO_HUESPED, Nullable<decimal> p_RUT_HUESPED, string p_DV_RUT_HUESPED, Nullable<decimal> p_TELEFONO_HUESPED, string p_CORREO_HUESPED, Nullable<decimal> p_ID_EMPRESA)
        {
            var p_NOMBRE_HUESPEDParameter = p_NOMBRE_HUESPED != null ?
                new ObjectParameter("P_NOMBRE_HUESPED", p_NOMBRE_HUESPED) :
                new ObjectParameter("P_NOMBRE_HUESPED", typeof(string));
    
            var p_APELLIDO_HUESPEDParameter = p_APELLIDO_HUESPED != null ?
                new ObjectParameter("P_APELLIDO_HUESPED", p_APELLIDO_HUESPED) :
                new ObjectParameter("P_APELLIDO_HUESPED", typeof(string));
    
            var p_RUT_HUESPEDParameter = p_RUT_HUESPED.HasValue ?
                new ObjectParameter("P_RUT_HUESPED", p_RUT_HUESPED) :
                new ObjectParameter("P_RUT_HUESPED", typeof(decimal));
    
            var p_DV_RUT_HUESPEDParameter = p_DV_RUT_HUESPED != null ?
                new ObjectParameter("P_DV_RUT_HUESPED", p_DV_RUT_HUESPED) :
                new ObjectParameter("P_DV_RUT_HUESPED", typeof(string));
    
            var p_TELEFONO_HUESPEDParameter = p_TELEFONO_HUESPED.HasValue ?
                new ObjectParameter("P_TELEFONO_HUESPED", p_TELEFONO_HUESPED) :
                new ObjectParameter("P_TELEFONO_HUESPED", typeof(decimal));
    
            var p_CORREO_HUESPEDParameter = p_CORREO_HUESPED != null ?
                new ObjectParameter("P_CORREO_HUESPED", p_CORREO_HUESPED) :
                new ObjectParameter("P_CORREO_HUESPED", typeof(string));
    
            var p_ID_EMPRESAParameter = p_ID_EMPRESA.HasValue ?
                new ObjectParameter("P_ID_EMPRESA", p_ID_EMPRESA) :
                new ObjectParameter("P_ID_EMPRESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_HUESPED", p_NOMBRE_HUESPEDParameter, p_APELLIDO_HUESPEDParameter, p_RUT_HUESPEDParameter, p_DV_RUT_HUESPEDParameter, p_TELEFONO_HUESPEDParameter, p_CORREO_HUESPEDParameter, p_ID_EMPRESAParameter);
        }
    
        public virtual int INSERTAR_MENU(string p_NOMBRE_MENU, Nullable<decimal> p_TIPO_MENU, Nullable<decimal> p_ESTILO_MENU, string p_DESCRIPCION_MENU, Nullable<decimal> p_VALOR_MENU, Nullable<decimal> p_CANTIDAD_MENU, Nullable<decimal> p_ESTADO_MENU)
        {
            var p_NOMBRE_MENUParameter = p_NOMBRE_MENU != null ?
                new ObjectParameter("P_NOMBRE_MENU", p_NOMBRE_MENU) :
                new ObjectParameter("P_NOMBRE_MENU", typeof(string));
    
            var p_TIPO_MENUParameter = p_TIPO_MENU.HasValue ?
                new ObjectParameter("P_TIPO_MENU", p_TIPO_MENU) :
                new ObjectParameter("P_TIPO_MENU", typeof(decimal));
    
            var p_ESTILO_MENUParameter = p_ESTILO_MENU.HasValue ?
                new ObjectParameter("P_ESTILO_MENU", p_ESTILO_MENU) :
                new ObjectParameter("P_ESTILO_MENU", typeof(decimal));
    
            var p_DESCRIPCION_MENUParameter = p_DESCRIPCION_MENU != null ?
                new ObjectParameter("P_DESCRIPCION_MENU", p_DESCRIPCION_MENU) :
                new ObjectParameter("P_DESCRIPCION_MENU", typeof(string));
    
            var p_VALOR_MENUParameter = p_VALOR_MENU.HasValue ?
                new ObjectParameter("P_VALOR_MENU", p_VALOR_MENU) :
                new ObjectParameter("P_VALOR_MENU", typeof(decimal));
    
            var p_CANTIDAD_MENUParameter = p_CANTIDAD_MENU.HasValue ?
                new ObjectParameter("P_CANTIDAD_MENU", p_CANTIDAD_MENU) :
                new ObjectParameter("P_CANTIDAD_MENU", typeof(decimal));
    
            var p_ESTADO_MENUParameter = p_ESTADO_MENU.HasValue ?
                new ObjectParameter("P_ESTADO_MENU", p_ESTADO_MENU) :
                new ObjectParameter("P_ESTADO_MENU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_MENU", p_NOMBRE_MENUParameter, p_TIPO_MENUParameter, p_ESTILO_MENUParameter, p_DESCRIPCION_MENUParameter, p_VALOR_MENUParameter, p_CANTIDAD_MENUParameter, p_ESTADO_MENUParameter);
        }
    
        public virtual int INSERTAR_PROVEEDOR(string nOMBRE_PROVEEDOR, Nullable<decimal> cONTACTO_PROVEEDOR, string rUBRO_PROVEEDOR, string dIRECCION_PROVEEDOR, string cORREO_PROVEEDOR, Nullable<decimal> iD_PERFIL)
        {
            var nOMBRE_PROVEEDORParameter = nOMBRE_PROVEEDOR != null ?
                new ObjectParameter("NOMBRE_PROVEEDOR", nOMBRE_PROVEEDOR) :
                new ObjectParameter("NOMBRE_PROVEEDOR", typeof(string));
    
            var cONTACTO_PROVEEDORParameter = cONTACTO_PROVEEDOR.HasValue ?
                new ObjectParameter("CONTACTO_PROVEEDOR", cONTACTO_PROVEEDOR) :
                new ObjectParameter("CONTACTO_PROVEEDOR", typeof(decimal));
    
            var rUBRO_PROVEEDORParameter = rUBRO_PROVEEDOR != null ?
                new ObjectParameter("RUBRO_PROVEEDOR", rUBRO_PROVEEDOR) :
                new ObjectParameter("RUBRO_PROVEEDOR", typeof(string));
    
            var dIRECCION_PROVEEDORParameter = dIRECCION_PROVEEDOR != null ?
                new ObjectParameter("DIRECCION_PROVEEDOR", dIRECCION_PROVEEDOR) :
                new ObjectParameter("DIRECCION_PROVEEDOR", typeof(string));
    
            var cORREO_PROVEEDORParameter = cORREO_PROVEEDOR != null ?
                new ObjectParameter("CORREO_PROVEEDOR", cORREO_PROVEEDOR) :
                new ObjectParameter("CORREO_PROVEEDOR", typeof(string));
    
            var iD_PERFILParameter = iD_PERFIL.HasValue ?
                new ObjectParameter("ID_PERFIL", iD_PERFIL) :
                new ObjectParameter("ID_PERFIL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_PROVEEDOR", nOMBRE_PROVEEDORParameter, cONTACTO_PROVEEDORParameter, rUBRO_PROVEEDORParameter, dIRECCION_PROVEEDORParameter, cORREO_PROVEEDORParameter, iD_PERFILParameter);
        }
    
        public virtual int INSERTAR_USUARIO(string nOMBRE_USUARIO, string aPELLIDO_USUARIO, string uSERNAME, string pASS, Nullable<decimal> eSTADO_PASS, Nullable<decimal> iD_PERFIL, Nullable<decimal> iD_EMPRESA, Nullable<decimal> iD_PERFIL_2)
        {
            var nOMBRE_USUARIOParameter = nOMBRE_USUARIO != null ?
                new ObjectParameter("NOMBRE_USUARIO", nOMBRE_USUARIO) :
                new ObjectParameter("NOMBRE_USUARIO", typeof(string));
    
            var aPELLIDO_USUARIOParameter = aPELLIDO_USUARIO != null ?
                new ObjectParameter("APELLIDO_USUARIO", aPELLIDO_USUARIO) :
                new ObjectParameter("APELLIDO_USUARIO", typeof(string));
    
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            var pASSParameter = pASS != null ?
                new ObjectParameter("PASS", pASS) :
                new ObjectParameter("PASS", typeof(string));
    
            var eSTADO_PASSParameter = eSTADO_PASS.HasValue ?
                new ObjectParameter("ESTADO_PASS", eSTADO_PASS) :
                new ObjectParameter("ESTADO_PASS", typeof(decimal));
    
            var iD_PERFILParameter = iD_PERFIL.HasValue ?
                new ObjectParameter("ID_PERFIL", iD_PERFIL) :
                new ObjectParameter("ID_PERFIL", typeof(decimal));
    
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(decimal));
    
            var iD_PERFIL_2Parameter = iD_PERFIL_2.HasValue ?
                new ObjectParameter("ID_PERFIL_2", iD_PERFIL_2) :
                new ObjectParameter("ID_PERFIL_2", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_USUARIO", nOMBRE_USUARIOParameter, aPELLIDO_USUARIOParameter, uSERNAMEParameter, pASSParameter, eSTADO_PASSParameter, iD_PERFILParameter, iD_EMPRESAParameter, iD_PERFIL_2Parameter);
        }
    
        public virtual int LIBERAR_COMEDOR(Nullable<decimal> p_ID_COMEDOR)
        {
            var p_ID_COMEDORParameter = p_ID_COMEDOR.HasValue ?
                new ObjectParameter("P_ID_COMEDOR", p_ID_COMEDOR) :
                new ObjectParameter("P_ID_COMEDOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LIBERAR_COMEDOR", p_ID_COMEDORParameter);
        }
    
        public virtual int LIBERAR_HABITACION(Nullable<decimal> p_ID_HABITACION)
        {
            var p_ID_HABITACIONParameter = p_ID_HABITACION.HasValue ?
                new ObjectParameter("P_ID_HABITACION", p_ID_HABITACION) :
                new ObjectParameter("P_ID_HABITACION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LIBERAR_HABITACION", p_ID_HABITACIONParameter);
        }
    
        public virtual int INSERTAR_PRODUCTO(string p_NOMBRE_PRODUCTO, Nullable<decimal> p_STOCK_PRODUCTO, Nullable<decimal> p_ID_PROVEEDOR, Nullable<decimal> p_ESTADO_PRODUCTO)
        {
            var p_NOMBRE_PRODUCTOParameter = p_NOMBRE_PRODUCTO != null ?
                new ObjectParameter("P_NOMBRE_PRODUCTO", p_NOMBRE_PRODUCTO) :
                new ObjectParameter("P_NOMBRE_PRODUCTO", typeof(string));
    
            var p_STOCK_PRODUCTOParameter = p_STOCK_PRODUCTO.HasValue ?
                new ObjectParameter("P_STOCK_PRODUCTO", p_STOCK_PRODUCTO) :
                new ObjectParameter("P_STOCK_PRODUCTO", typeof(decimal));
    
            var p_ID_PROVEEDORParameter = p_ID_PROVEEDOR.HasValue ?
                new ObjectParameter("P_ID_PROVEEDOR", p_ID_PROVEEDOR) :
                new ObjectParameter("P_ID_PROVEEDOR", typeof(decimal));
    
            var p_ESTADO_PRODUCTOParameter = p_ESTADO_PRODUCTO.HasValue ?
                new ObjectParameter("P_ESTADO_PRODUCTO", p_ESTADO_PRODUCTO) :
                new ObjectParameter("P_ESTADO_PRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_PRODUCTO", p_NOMBRE_PRODUCTOParameter, p_STOCK_PRODUCTOParameter, p_ID_PROVEEDORParameter, p_ESTADO_PRODUCTOParameter);
        }
    
        public virtual int INSERTAR_ORDEN_PEDIDO(Nullable<decimal> p_ID_PROVEEDOR, string p_PRODUCTOS_CODIGOS, Nullable<decimal> p_CANTIDAD_PRODUCTO, Nullable<decimal> p_CODIGO_ORDEN_PEDIDO)
        {
            var p_ID_PROVEEDORParameter = p_ID_PROVEEDOR.HasValue ?
                new ObjectParameter("P_ID_PROVEEDOR", p_ID_PROVEEDOR) :
                new ObjectParameter("P_ID_PROVEEDOR", typeof(decimal));
    
            var p_PRODUCTOS_CODIGOSParameter = p_PRODUCTOS_CODIGOS != null ?
                new ObjectParameter("P_PRODUCTOS_CODIGOS", p_PRODUCTOS_CODIGOS) :
                new ObjectParameter("P_PRODUCTOS_CODIGOS", typeof(string));
    
            var p_CANTIDAD_PRODUCTOParameter = p_CANTIDAD_PRODUCTO.HasValue ?
                new ObjectParameter("P_CANTIDAD_PRODUCTO", p_CANTIDAD_PRODUCTO) :
                new ObjectParameter("P_CANTIDAD_PRODUCTO", typeof(decimal));
    
            var p_CODIGO_ORDEN_PEDIDOParameter = p_CODIGO_ORDEN_PEDIDO.HasValue ?
                new ObjectParameter("P_CODIGO_ORDEN_PEDIDO", p_CODIGO_ORDEN_PEDIDO) :
                new ObjectParameter("P_CODIGO_ORDEN_PEDIDO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_ORDEN_PEDIDO", p_ID_PROVEEDORParameter, p_PRODUCTOS_CODIGOSParameter, p_CANTIDAD_PRODUCTOParameter, p_CODIGO_ORDEN_PEDIDOParameter);
        }
    }
}
