//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspOracle.Models.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int ID_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public Nullable<int> STOCK_PRODUCTO { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public Nullable<int> ESTADO_PRODUCTO { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
